import importlib.resources
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml

from .config import home, write_json

MARKER = "Generated by Auto local — SSHDotCodes/auto"


def agent_root(agent):
    if agent == "pi":
        return Path(os.environ.get("PI_CODING_AGENT_DIR", Path.home() / ".pi" / "agent"))
    if agent == "opencode":
        return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "opencode"
    if agent == "hermes":
        return Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes"))
    raise ValueError("agent must be pi, opencode, or hermes")


def owned_write(path, text):
    if path.exists() and MARKER not in path.read_text(encoding="utf-8"):
        raise ValueError(f"Refusing to overwrite an existing file: {path}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def enable_hermes(root, enable=True):
    path = root / "config.yaml"
    previous = path.read_text(encoding="utf-8") if path.exists() else ""
    config = yaml.safe_load(previous) or {}
    if not isinstance(config, dict):
        raise ValueError("Hermes config must be a YAML mapping")
    plugins = config.setdefault("plugins", {})
    enabled = plugins.setdefault("enabled", [])
    if not isinstance(enabled, list):
        raise ValueError("Hermes plugins.enabled must be a list")
    if enable and "auto" not in enabled:
        enabled.append("auto")
    if not enable:
        plugins["enabled"] = [x for x in enabled if x != "auto"]
    if previous:
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%f")
        backup = path.with_name("config.yaml.auto-backup-" + stamp)
        shutil.copy2(path, backup)
        if os.name != "nt":
            os.chmod(backup, 0o600)
    root.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")
    if os.name != "nt":
        os.chmod(path, 0o600)


def install_agent(agent, root=None):
    root = root or agent_root(agent)
    resources = Path(str(importlib.resources.files("auto_gate"))) / "adapters"
    config = {"python": sys.executable, "autoHome": str(home()), "timeoutMs": 145000}
    if agent in {"pi", "opencode"}:
        folder = "extensions" if agent == "pi" else "plugins"
        path = root / folder / "zz-auto.ts"
        factory = "piPlugin" if agent == "pi" else "opencodePlugin"
        source = resources / (agent + ".mjs")
        code = f"// {MARKER}\nimport {{{factory}}} from {json.dumps(source.as_uri())};\nexport default {factory}({json.dumps(config)});\n"
        owned_write(path, code)
        paths = [path]
    else:
        folder = root / "plugins" / "auto"
        path = folder / "__init__.py"
        code = f"""# {MARKER}
import importlib.util
_spec = importlib.util.spec_from_file_location("auto_hermes_adapter", {str(resources / "hermes.py")!r})
_module = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_module)
def register(ctx):
    return _module.register_with(ctx, {sys.executable!r}, {str(home())!r})
"""
        owned_write(path, code)
        manifest = folder / "plugin.yaml"
        owned_write(
            manifest,
            f"# {MARKER}\nname: auto\nversion: '0.1.0'\ndescription: Local Auto tool-call classification\n",
        )
        enable_hermes(root)
        paths = [path, manifest]
    registry_path = home() / "installations.json"
    registry = json.loads(registry_path.read_text()) if registry_path.exists() else {}
    registry[agent] = {"root": str(root), "paths": [str(p) for p in paths]}
    write_json(registry_path, registry)
    return [str(p) for p in paths]


def uninstall_agent(agent):
    registry_path = home() / "installations.json"
    registry = json.loads(registry_path.read_text()) if registry_path.exists() else {}
    entry = registry.get(agent)
    if not entry:
        return []
    removed = []
    for name in entry["paths"]:
        path = Path(name)
        if path.exists() and MARKER in path.read_text(encoding="utf-8"):
            path.unlink()
            removed.append(name)
    if agent == "hermes":
        enable_hermes(Path(entry["root"]), enable=False)
    del registry[agent]
    write_json(registry_path, registry)
    return removed
